import AboutUs from "@/modules/components/AboutUs";
import { ConfirmationCard } from "@/modules/components/ConfirmationCard";
import Gift from "@/modules/components/Gift";
import { ImageCard } from "@/modules/components/ImageCard";
import { NavigationHeader } from "@/modules/components/NavigationHeader";
import { Presentation } from "@/modules/components/Presentation";
import SongsSugestions from "@/modules/components/SongsSugestions";
import { WelcomeTextCard } from "@/modules/components/WelcomeTextCard";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>¡Nos casamos!</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, height=device-height, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center bg-grey-bg">
        <main className="flex flex-col bg-grey-bg">
          <div className="flex flex-col items-center font-sans max-w-5xl">
            <NavigationHeader />
            <Presentation />
            <WelcomeTextCard />
            <AboutUs />
            <div className="w-full flex flex-col lg:flex-row">
              <ImageCard
                imageSrc={`${process.env.NEXT_PUBLIC_IMAGES_ROUTE}images/ceremonia.png`}
                srcUrl="https://maps.app.goo.gl/GQdfLSD8Wrdv5raV8"
                imageAlt="Imagen de Na Capitana, donde nos casamos"
                title="LA CEREMONIA"
                subtitle="12:30 - Na Capitana"
              />
              <ImageCard
                imageSrc={`${process.env.NEXT_PUBLIC_IMAGES_ROUTE}images/festin.png`}
                srcUrl="https://maps.app.goo.gl/GQdfLSD8Wrdv5raV8"
                imageAlt="Imagen de Na Capitana, donde celebramos el banquete"
                title="LA FIESTA"
                subtitle="14:00 - Na Capitana"
              />
            </div>
            <ConfirmationCard />
            <Gift />
            <SongsSugestions />
          </div>
        </main>
      </div>
    </>
  );
}
